### PR TITLE
Update for os-version variables

### PR DESCRIPTION
**Pull request by oliverhowell**
Based on https://github.com/hazelcast/hz-docs/pull/1355/files but we didn't backport so need to update variables on this page and check/remove sections that are removed in other PR - are they still applicable for this version @TomaszGaweda ?

### CODE REVIEW

**Review by TomaszGaweda — APPROVED** [review]
Thanks!

**Review by Rob-Hazelcast — APPROVED** [review]
The variable appears to be working, though the page is pretty broken in the preview build. Hopefully that's as expected.

**Comment by oliverhowell** [comment]
Yeah, that's not right - I'll take another look and push up a fix

**Comment by oliverhowell** [comment]
Closing in favour of https://github.com/hazelcast/hz-docs/pull/1447

**Pull request closed without merging**
