### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by yuce**

### CODE REVIEW

**Review by pmcgleenon — APPROVED** [review]

**Review by JackPGreen — APPROVED** [review]

**Comment by JackPGreen** [comment]
@yuce can you do this in `main`, please? Or change the target to `main` and add the backport label(s)?

**Comment by JackPGreen** [comment]
> > @yuce can you do this in `main`, please? Or change the target to `main` and add the backport label(s)?
> 
> AFAIK `main` is not up-to-date with the changes in `v/5.5`. @oliverhowell Is it OK to target `v/5.5`? Otherwise how should we handle this?

It's the same in `main`:
https://github.com/hazelcast/hz-docs/blob/main/docs/modules/security/pages/tls-ssl.adoc?plain=1

**Review by oliverhowell — APPROVED** [review]

**Comment by oliverhowell** [comment]
I fixed main too, thanks

**Comment by oliverhowell** [comment]
There's a build error tho..

**Pull request closed without merging**
