### PR TITLE
Updated the doc

### PR DESCRIPTION
**Pull request by Karnav123**
The original line seems to be incorrect.

### CODE REVIEW

**Review by Serdaro — APPROVED** [review]

**Comment by Serdaro** [comment]
Thanks a lot @Karnav123

**Comment by Karnav123** [comment]
@Serdaro @devOpsHazelcast The pipeline is failing in check-link step, however I have not modified any links. What should be done here?

**Comment by Serdaro** [comment]
@Karnav123 , nothing really. It is an internal link checker. I will put backporting labels. You can then merge it.

**Comment by Karnav123** [comment]
> @Karnav123 , nothing really. It is an internal link checker. I will put backporting labels. You can then merge it.

Thanks for this. I do not have write access to merge this pull request, It will be great if you can do it or else guide me. Thanks in advance!

**Pull request merged**
