### PR TITLE
Remove specific netty and netty-tcnative versions from the integrating-openssl page

### PR DESCRIPTION
**Pull request by kwart**

### CODE REVIEW

**Review by Serdaro — APPROVED** [review]

**Review by semihbkgr — COMMENTED** [review]
As of `2.0.46-Final` java classes are separated from `netty.tcnative` and released as new Jar called `netty-tcnative-classes`. So It is required to add `netty-tcnative-classes` Jar for both OpenSSL and BoringSSL If using `2.0.46-Final` or later versions.

**Comment by kwart** [comment]
> As of `2.0.46-Final` java classes are separated from `netty.tcnative` and released as new Jar called `netty-tcnative-classes`. So It is required to add `netty-tcnative-classes` Jar for both OpenSSL and BoringSSL If using `2.0.46-Final` or later versions.

According to the dependency tree, the `netty-tcnative-classes` is provided as a transitive dependency:
```
[INFO] +- io.netty:netty-tcnative-boringssl-static:jar:2.0.61.Final:provided
[INFO] |  +- io.netty:netty-tcnative-classes:jar:2.0.61.Final:provided
[INFO] |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.61.Final:provided
[INFO] |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.61.Final:provided
[INFO] |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-x86_64:2.0.61.Final:provided
[INFO] |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-aarch_64:2.0.61.Final:provided
[INFO] |  \- io.netty:netty-tcnative-boringssl-static:jar:windows-x86_64:2.0.61.Final:provided
[INFO] +- io.netty:netty-handler:jar:4.1.92.Final:provided
[INFO] |  +- io.netty:netty-common:jar:4.1.92.Final:provided
[INFO] |  +- io.netty:netty-resolver:jar:4.1.92.Final:provided
[INFO] |  +- io.netty:netty-buffer:jar:4.1.92.Final:provided
[INFO] |  +- io.netty:netty-transport:jar:4.1.92.Final:provided
[INFO] |  +- io.netty:netty-transport-native-unix-common:jar:4.1.92.Final:provided
[INFO] |  \- io.netty:netty-codec:jar:4.1.92.Final:provided
```

**Comment by Serdaro** [comment]
@kwart , @semihbkgr , I was wondering what is the latest news on this one. Using only the `netty-handler` is enough?

**Comment by kwart** [comment]
I think, the dependencies we list are correct. The only issue was listing the exact versions.

**Comment by kwart** [comment]
> When I run Hazelcast container adding only these two dependencies into the classpath, I got this error:

From the stacktrace it seems you don't run it from Maven, but rather as from distribution through `hz start`, or am I wrong?

**Comment by semihbkgr** [comment]
Yes, you are right. I am running Hazelcast default container by adding required jars to the classpath.

**Comment by kwart** [comment]
> Yes, you are right. I am running Hazelcast default container by adding required jars to the classpath.

I've added a new commit to improve the wording about dependencies.

**Review by semihbkgr — APPROVED** [review]

**Pull request merged**
